/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bpkassa;

import java.awt.Color;

/**
 *
 * @author Rheo
 */
public class hoofdscherm extends javax.swing.JFrame {

    /**
     * Creates new form hoofdscherm
     */
    double prijzen [];
    int clicks[];
    int kortingclick = 0;
    
    
    public double totaalPrijs(double[] prijzen, int[] clicks){
        double Totaal = 0;
        int i;
        for (i=0; i < prijzen.length; i++){
            Totaal = Totaal +  (prijzen[i] * clicks[i]);
            
        }
        return (Totaal);
    }
  

        
    public hoofdscherm() {
        prijzen = new double[10];
        prijzen[0]= 7.50; //mojito
        prijzen[1]= 6.50; //bloody mary
        prijzen[2]= 5.50; // twelve fill
        prijzen[3]= 6.75; // scotch
        prijzen[4]= 5.50; // vodka
        prijzen[5]= 6; //bier
        prijzen[6]= 4; //cola
        prijzen[7] = 4;//korting
        prijzen[8] = 0.10; // korting
        prijzen[9] = 0.21;//btw  
        
        //clicks 
        clicks = new int[10];
        clicks[0]=0;
        clicks[1]=0;
        clicks[2]=0;
        clicks[3]=0;
        clicks[4]=0;
        clicks[5]=0;
        clicks[6]=0;
        clicks[7]=0;
        clicks[8]=0;
        clicks[9]=0;
        
        
       
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMargarita = new javax.swing.JButton();
        btnMojito = new javax.swing.JButton();
        btnBloody = new javax.swing.JButton();
        btnScotch = new javax.swing.JButton();
        btnVodka = new javax.swing.JButton();
        btnBier = new javax.swing.JButton();
        btnKorting = new javax.swing.JButton();
        txtPrijs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JIM'S BAR KASSA");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 0, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1120, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMargarita.setBackground(new java.awt.Color(51, 102, 255));
        btnMargarita.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMargarita.setForeground(new java.awt.Color(51, 255, 51));
        btnMargarita.setText("Margarita");
        btnMargarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 100));

        btnMojito.setBackground(new java.awt.Color(51, 102, 255));
        btnMojito.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMojito.setForeground(new java.awt.Color(51, 255, 51));
        btnMojito.setText("Mojito");
        btnMojito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMojitoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMojito, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 180, 100));

        btnBloody.setBackground(new java.awt.Color(51, 102, 255));
        btnBloody.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBloody.setForeground(new java.awt.Color(51, 255, 51));
        btnBloody.setText("Bloody Mary");
        btnBloody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodyActionPerformed(evt);
            }
        });
        getContentPane().add(btnBloody, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 100));

        btnScotch.setBackground(new java.awt.Color(51, 102, 255));
        btnScotch.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnScotch.setForeground(new java.awt.Color(51, 255, 51));
        btnScotch.setText("Scotch ");
        btnScotch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScotchActionPerformed(evt);
            }
        });
        getContentPane().add(btnScotch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, 100));

        btnVodka.setBackground(new java.awt.Color(51, 102, 255));
        btnVodka.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnVodka.setForeground(new java.awt.Color(51, 255, 51));
        btnVodka.setText("Vodka");
        btnVodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVodkaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVodka, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 110));

        btnBier.setBackground(new java.awt.Color(51, 102, 255));
        btnBier.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBier.setForeground(new java.awt.Color(51, 255, 51));
        btnBier.setText("Bier");
        btnBier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBierActionPerformed(evt);
            }
        });
        getContentPane().add(btnBier, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, 110));

        btnKorting.setBackground(new java.awt.Color(255, 0, 0));
        btnKorting.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnKorting.setText("10% KORTING");
        btnKorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKortingActionPerformed(evt);
            }
        });
        getContentPane().add(btnKorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 340, 60));

        txtPrijs.setEditable(false);
        txtPrijs.setBackground(new java.awt.Color(0, 0, 0));
        txtPrijs.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtPrijs.setForeground(new java.awt.Color(0, 204, 102));
        getContentPane().add(txtPrijs, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 340, 90));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("PRIJS TOT NU TOE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -20, 380, 140));

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 1, 48)); // NOI18N
        jLabel2.setText("JIM'S BAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 370, 360));

        jLabel3.setFont(new java.awt.Font("Brush Script MT", 1, 48)); // NOI18N
        jLabel3.setText("WELKOM ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -90, 370, 360));

        jLabel4.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel4.setText("BIJ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -50, 370, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rheo\\OneDrive - De Haagse Hogeschool\\HBO ICT\\Programming\\New Folder\\bpKassa\\587e338e9686194a55adab7e.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 350, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 740, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rheo\\OneDrive - De Haagse Hogeschool\\HBO ICT\\Programming\\New Folder\\bpKassa\\587e33959686194a55adab7f.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 350, 430));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rheo\\OneDrive - De Haagse Hogeschool\\HBO ICT\\Programming\\New Folder\\bpKassa\\Mojito-PNG-Transparent-Image.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, 530));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rheo\\OneDrive - De Haagse Hogeschool\\HBO ICT\\Programming\\New Folder\\bpKassa\\xxl_scotch-whiskey.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 430, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rheo\\OneDrive - De Haagse Hogeschool\\HBO ICT\\Programming\\New Folder\\bpKassa\\Beer_PNG_Clip_Art.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 250, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rheo\\OneDrive - De Haagse Hogeschool\\HBO ICT\\Programming\\New Folder\\bpKassa\\vod.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMargaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMargaritaActionPerformed
     clicks[0]++;
     txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
        
     
     
    }//GEN-LAST:event_btnMargaritaActionPerformed

    private void btnScotchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScotchActionPerformed
        clicks[4]++;

       txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
       
    }//GEN-LAST:event_btnScotchActionPerformed

    private void btnMojitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMojitoActionPerformed
        clicks[1]++;
        txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnMojitoActionPerformed

    private void btnVodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVodkaActionPerformed
       clicks[5]++;
      
       txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnVodkaActionPerformed

    private void btnBloodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodyActionPerformed
       clicks[3]++;
       txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnBloodyActionPerformed

    private void btnBierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBierActionPerformed
        clicks[6]++;
        txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnBierActionPerformed

    private void btnKortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKortingActionPerformed
   kortingclick++;
     if(kortingclick%2 !=0){
     btnKorting.setBackground(Color.GREEN);
   
    }//GEN-LAST:event_btnKortingActionPerformed
    else{
        btnKorting.setBackground(Color.RED);
    }
    }
    
    
    /**
     * 
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoofdscherm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBier;
    private javax.swing.JButton btnBloody;
    private javax.swing.JButton btnKorting;
    private javax.swing.JButton btnMargarita;
    private javax.swing.JButton btnMojito;
    private javax.swing.JButton btnScotch;
    private javax.swing.JButton btnVodka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtPrijs;
    // End of variables declaration//GEN-END:variables
}
