/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bpkassa;

import java.awt.Color;

/**
 *
 * @author Rheo
 */
public class hoofdscherm extends javax.swing.JFrame {

    /**
     * Creates new form hoofdscherm
     */
    double prijzen [];
    int clicks[];
    int kortingclick = 0;
    
    
    public double totaalPrijs(double[] prijzen, int[] clicks){
        double Totaal = 0;
        int i;
        for (i=0; i < prijzen.length; i++){
            Totaal = Totaal +  (prijzen[i] * clicks[i]);
            
        }
        return (Totaal);
    }
  

        
    public hoofdscherm() {
        prijzen = new double[10];
        prijzen[0]= 7.50; //mojito
        prijzen[1]= 6.50; //bloody mary
        prijzen[2]= 5.50; // twelve fill
        prijzen[3]= 6.75; // scotch
        prijzen[4]= 5.50; // vodka
        prijzen[5]= 6; //bier
        prijzen[6]= 4; //cola
        prijzen[7] = 4;//korting
        prijzen[8] = 0.10; // korting
        prijzen[9] = 0.21;//btw  
        
        //clicks 
        clicks = new int[10];
        clicks[0]=0;
        clicks[1]=0;
        clicks[2]=0;
        clicks[3]=0;
        clicks[4]=0;
        clicks[5]=0;
        clicks[6]=0;
        clicks[7]=0;
        clicks[8]=0;
        clicks[9]=0;
        
        
       
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMargarita = new javax.swing.JButton();
        btnMojito = new javax.swing.JButton();
        btnBloody = new javax.swing.JButton();
        btnScotch = new javax.swing.JButton();
        btnVodka = new javax.swing.JButton();
        btnBier = new javax.swing.JButton();
        btnKorting = new javax.swing.JButton();
        txtPrijs = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMargarita.setText("Margarita");
        btnMargarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMargaritaActionPerformed(evt);
            }
        });

        btnMojito.setText("Mojito");
        btnMojito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMojitoActionPerformed(evt);
            }
        });

        btnBloody.setText("Bloody Mary");
        btnBloody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodyActionPerformed(evt);
            }
        });

        btnScotch.setText("Scotch ");
        btnScotch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScotchActionPerformed(evt);
            }
        });

        btnVodka.setText("Vodka");
        btnVodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVodkaActionPerformed(evt);
            }
        });

        btnBier.setText("Bier");
        btnBier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBierActionPerformed(evt);
            }
        });

        btnKorting.setBackground(new java.awt.Color(255, 0, 0));
        btnKorting.setText("10% korting");
        btnKorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKortingActionPerformed(evt);
            }
        });

        jLabel1.setText("prijs tot nu toe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBloody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMojito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMargarita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScotch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVodka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(330, 330, 330)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnKorting))
                .addGap(18, 18, 18)
                .addComponent(txtPrijs, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMargarita)
                    .addComponent(btnKorting))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMojito)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrijs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(btnBloody)
                .addGap(18, 18, 18)
                .addComponent(btnScotch)
                .addGap(18, 18, 18)
                .addComponent(btnVodka)
                .addGap(18, 18, 18)
                .addComponent(btnBier)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMargaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMargaritaActionPerformed
     clicks[0]++;
     txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
        
     
     
    }//GEN-LAST:event_btnMargaritaActionPerformed

    private void btnScotchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScotchActionPerformed
        clicks[4]++;

       txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
       
    }//GEN-LAST:event_btnScotchActionPerformed

    private void btnMojitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMojitoActionPerformed
        clicks[1]++;
        txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnMojitoActionPerformed

    private void btnVodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVodkaActionPerformed
       clicks[5]++;
      
       txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnVodkaActionPerformed

    private void btnBloodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodyActionPerformed
       clicks[3]++;
       txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnBloodyActionPerformed

    private void btnBierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBierActionPerformed
        clicks[6]++;
        txtPrijs.setText(""+totaalPrijs(prijzen, clicks));
    }//GEN-LAST:event_btnBierActionPerformed

    private void btnKortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKortingActionPerformed
   kortingclick++;
     if(kortingclick%2 !=0){
     btnKorting.setBackground(Color.GREEN);
   
    }//GEN-LAST:event_btnKortingActionPerformed
    else{
        btnKorting.setBackground(Color.RED);
    }
    }
    
    
    /**
     * 
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoofdscherm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBier;
    private javax.swing.JButton btnBloody;
    private javax.swing.JButton btnKorting;
    private javax.swing.JButton btnMargarita;
    private javax.swing.JButton btnMojito;
    private javax.swing.JButton btnScotch;
    private javax.swing.JButton btnVodka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPrijs;
    // End of variables declaration//GEN-END:variables
}
